### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by jponge**
This updates the plugin to Gradle at Eclipse, among other things.

### CODE REVIEW

**Comment by jponge** [comment]
@erdi This is open for review.

BTW the last commit is an update to Gradle 2.6, but there are 2 similar failures in the test:

```
java.lang.IllegalStateException: Cannot get an instance of NativeServices without first calling initialize().
	at org.gradle.internal.nativeintegration.services.NativeServices.getInstance(NativeServices.java:85)
	at org.gradle.internal.nativeintegration.services.FileSystems.getDefault(FileSystems.java:22)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.<init>(DirectoryFileTree.java:56)
	at org.gradle.api.internal.file.DefaultSourceDirectorySet.doGetSrcDirTrees(DefaultSourceDirectorySet.java:147)
	at org.gradle.api.internal.file.DefaultSourceDirectorySet.getSrcDirTrees(DefaultSourceDirectorySet.java:128)
	at org.gradle.api.internal.file.DefaultSourceDirectorySet.getSrcDirs(DefaultSourceDirectorySet.java:57)
	at org.gololang.gradle.test.GoloSourceSetSpec.can configure source set(GoloSourceSetSpec.groovy:48)
```

**Comment by erdi** [comment]
Will have a look at your changes and also upgrade it to use the new Gradle Test Kit for integration tests instead of using a custom made solution. Also, I think I know what is causing the error you're seeing.

**Comment by jponge** [comment]
:+1: @erdi

**Comment by erdi** [comment]
Sorry that it took so long, especially as the fix was trivial, I've been pretty busy lately. Noting was broken, it was just the unit tests that needed some additional initialisation.

**Comment by jponge** [comment]
Thanks!

**Pull request merged**
